services:
  app:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}
    depends_on:
      - db
      - cache
    environment:
      BUNDLE_FROZEN: "false"
      CALENDLY_CLIENT_ID: ${CALENDLY_CLIENT_ID}
      CALENDLY_CLIENT_SECRET: ${CALENDLY_CLIENT_SECRET}
      CALENDLY_REDIRECT_URI: ${CALENDLY_REDIRECT_URI}
      DATABASE_URL: postgres://postgres:password@db:5432/tidr_${RAILS_ENV:-development}
      DROPBOX_CLIENT_ID: ${DROPBOX_CLIENT_ID}
      DROPBOX_CLIENT_SECRET: ${DROPBOX_CLIENT_SECRET}
      PORT: 3000
      RAILS_ENV: development
      REDIS_URL: redis://cache:6379/1
      ZOOM_CLIENT_ID: ${ZOOM_CLIENT_ID}
      ZOOM_CLIENT_SECRET: ${ZOOM_CLIENT_SECRET}
      ZOOM_REDIRECT_URI: ${ZOOM_REDIRECT_URI}
      ZOOM_VERIFICATION_TOKEN: ${ZOOM_VERIFICATION_TOKEN}
      ZOOM_WEBHOOK_SECRET_TOKEN: ${ZOOM_WEBHOOK_SECRET_TOKEN}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    tty: true
    volumes:
      - .:/tidr
    working_dir: /tidr

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tidr_${RAILS_ENV:-development}
      RAILS_ENV: development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db_data:
