services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
      - cache
    environment:
      CALENDLY_CLIENT_ID: ${CALENDLY_CLIENT_ID}
      CALENDLY_CLIENT_SECRET: ${CALENDLY_CLIENT_SECRET}
      CALENDLY_REDIRECT_URI: ${CALENDLY_REDIRECT_URI}
      DROPBOX_CLIENT_ID: ${DROPBOX_CLIENT_ID}
      DROPBOX_CLIENT_SECRET: ${DROPBOX_CLIENT_SECRET}
      DROPBOX_REDIRECT_URI: ${DROPBOX_REDIRECT_URI}
      PORT: ${PORT:-3000}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_HOST: db
      RAILS_ENV: ${RAILS_ENV:-development}
      REDIS_URL: redis://cache:${CACHE_PORT:-6379}/1
      ZOOM_CLIENT_ID: ${ZOOM_CLIENT_ID}
      ZOOM_CLIENT_SECRET: ${ZOOM_CLIENT_SECRET}
      ZOOM_REDIRECT_URI: ${ZOOM_REDIRECT_URI}
      ZOOM_VERIFICATION_TOKEN: ${ZOOM_VERIFICATION_TOKEN}
      ZOOM_WEBHOOK_SECRET_TOKEN: ${ZOOM_WEBHOOK_SECRET_TOKEN}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    tty: true
    volumes:
      - .:/tidr
    working_dir: /tidr

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: tidr_${RAILS_ENV:-development}
      RAILS_ENV: ${RAILS_ENV:-development}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"

  cache:
    image: redis:latest
    ports:
      - "${CACHE_PORT:-6379}:${CACHE_PORT:-6379}"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared.yml:/etc/cloudflared/config.yml
      - ./a3e77d67-1ac6-40ba-ae1b-82a65d1377e0.json:/etc/cloudflared/a3e77d67-1ac6-40ba-ae1b-82a65d1377e0.json
    depends_on:
      - app

volumes:
  db_data:
