services:
  app:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}
    container_name: hello_world_app
    depends_on:
      - db
      - cache
    environment:
      BUNDLE_FROZEN: "false"
      DATABASE_URL: postgres://postgres:password@db:5432/hello_world_app_${RAILS_ENV:-development}
      PORT: 3000
      RAILS_ENV: development
      REDIS_URL: redis://cache:6379/1
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: hellow_world_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hello_world_app_${RAILS_ENV:-development}
      RAILS_ENV: development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    container_name: hello_world_app_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
